package com.bhyf.common.wsclient.onecard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ThirdWebserviceSoap", targetNamespace = "http://www.hzsun.com/")
public interface ThirdWebserviceSoap {

	/**
	 * ��ȡϵͳ����(Json)
	 * 
	 * @param getSystemParamResult
	 * @param data
	 */
	@WebMethod(operationName = "GetSystemParam", action = "http://www.hzsun.com/GetSystemParam")
	@RequestWrapper(localName = "GetSystemParam", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParam")
	@ResponseWrapper(localName = "GetSystemParamResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParamResponse")
	public void getSystemParam(
			@WebParam(name = "GetSystemParamResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getSystemParamResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡϵͳ����(Xml)
	 * 
	 * @param getSystemParamForXmlResult
	 * @param data
	 */
	@WebMethod(operationName = "GetSystemParamForXml", action = "http://www.hzsun.com/GetSystemParamForXml")
	@RequestWrapper(localName = "GetSystemParamForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParamForXml")
	@ResponseWrapper(localName = "GetSystemParamForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParamForXmlResponse")
	public void getSystemParamForXml(
			@WebParam(name = "GetSystemParamForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getSystemParamForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡϵͳ�汾��
	 * 
	 * @param getSystemParamVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetSystemParamVersion", action = "http://www.hzsun.com/GetSystemParamVersion")
	@RequestWrapper(localName = "GetSystemParamVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParamVersion")
	@ResponseWrapper(localName = "GetSystemParamVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetSystemParamVersionResponse")
	public void getSystemParamVersion(
			@WebParam(name = "GetSystemParamVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getSystemParamVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * ��ȡУ�����(Json)
	 * 
	 * @param data
	 * @param getAreaParamResult
	 */
	@WebMethod(operationName = "GetAreaParam", action = "http://www.hzsun.com/GetAreaParam")
	@RequestWrapper(localName = "GetAreaParam", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAreaParam")
	@ResponseWrapper(localName = "GetAreaParamResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAreaParamResponse")
	public void getAreaParam(
			@WebParam(name = "GetAreaParamResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAreaParamResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡУ�����(Xml)
	 * 
	 * @param data
	 * @param getAreaParamForXmlResult
	 */
	@WebMethod(operationName = "GetAreaParamForXml", action = "http://www.hzsun.com/GetAreaParamForXml")
	@RequestWrapper(localName = "GetAreaParamForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAreaParamForXml")
	@ResponseWrapper(localName = "GetAreaParamForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAreaParamForXmlResponse")
	public void getAreaParamForXml(
			@WebParam(name = "GetAreaParamForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAreaParamForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡУ��汾��
	 * 
	 * @param getAccAreaParamVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetAccAreaParamVersion", action = "http://www.hzsun.com/GetAccAreaParamVersion")
	@RequestWrapper(localName = "GetAccAreaParamVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccAreaParamVersion")
	@ResponseWrapper(localName = "GetAccAreaParamVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccAreaParamVersionResponse")
	public void getAccAreaParamVersion(
			@WebParam(name = "GetAccAreaParamVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccAreaParamVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * �޸�У�����
	 * 
	 * @param sThirdID
	 * @param sAreaName
	 * @param nAreaNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UploadArea", action = "http://www.hzsun.com/UploadArea")
	@WebResult(name = "UploadAreaResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UploadArea", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadArea")
	@ResponseWrapper(localName = "UploadAreaResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAreaResponse")
	public String uploadArea(
			@WebParam(name = "nAreaNum", targetNamespace = "http://www.hzsun.com/") int nAreaNum,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sAreaName", targetNamespace = "http://www.hzsun.com/") String sAreaName);

	/**
	 * ��ȡ��ݲ���(Json)
	 * 
	 * @param getAccClassResult
	 * @param data
	 */
	@WebMethod(operationName = "GetAccClass", action = "http://www.hzsun.com/GetAccClass")
	@RequestWrapper(localName = "GetAccClass", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClass")
	@ResponseWrapper(localName = "GetAccClassResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClassResponse")
	public void getAccClass(
			@WebParam(name = "GetAccClassResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccClassResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ��ݲ���(Xml)
	 * 
	 * @param data
	 * @param getAccClassForXmlResult
	 */
	@WebMethod(operationName = "GetAccClassForXml", action = "http://www.hzsun.com/GetAccClassForXml")
	@RequestWrapper(localName = "GetAccClassForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClassForXml")
	@ResponseWrapper(localName = "GetAccClassForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClassForXmlResponse")
	public void getAccClassForXml(
			@WebParam(name = "GetAccClassForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccClassForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ��ݲ���汾��
	 * 
	 * @param getAccClassVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetAccClassVersion", action = "http://www.hzsun.com/GetAccClassVersion")
	@RequestWrapper(localName = "GetAccClassVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClassVersion")
	@ResponseWrapper(localName = "GetAccClassVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccClassVersionResponse")
	public void getAccClassVersion(
			@WebParam(name = "GetAccClassVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccClassVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * �޸���ݲ���
	 * 
	 * @param sThirdID
	 * @param sClsName
	 * @param nClsNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UploadAccClass", action = "http://www.hzsun.com/UploadAccClass")
	@WebResult(name = "UploadAccClassResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UploadAccClass", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccClass")
	@ResponseWrapper(localName = "UploadAccClassResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccClassResponse")
	public String uploadAccClass(
			@WebParam(name = "nClsNum", targetNamespace = "http://www.hzsun.com/") int nClsNum,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sClsName", targetNamespace = "http://www.hzsun.com/") String sClsName);

	/**
	 * ��ȡ�ʻ����Ų���(Json)
	 * 
	 * @param data
	 * @param getAccDepartmentResult
	 */
	@WebMethod(operationName = "GetAccDepartment", action = "http://www.hzsun.com/GetAccDepartment")
	@RequestWrapper(localName = "GetAccDepartment", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartment")
	@ResponseWrapper(localName = "GetAccDepartmentResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartmentResponse")
	public void getAccDepartment(
			@WebParam(name = "GetAccDepartmentResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccDepartmentResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ�ʻ����Ų���(Xml)
	 * 
	 * @param data
	 * @param getAccDepartmentForXmlResult
	 */
	@WebMethod(operationName = "GetAccDepartmentForXml", action = "http://www.hzsun.com/GetAccDepartmentForXml")
	@RequestWrapper(localName = "GetAccDepartmentForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartmentForXml")
	@ResponseWrapper(localName = "GetAccDepartmentForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartmentForXmlResponse")
	public void getAccDepartmentForXml(
			@WebParam(name = "GetAccDepartmentForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccDepartmentForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ�ʻ����Ű汾��
	 * 
	 * @param getAccDepartmentVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetAccDepartmentVersion", action = "http://www.hzsun.com/GetAccDepartmentVersion")
	@RequestWrapper(localName = "GetAccDepartmentVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartmentVersion")
	@ResponseWrapper(localName = "GetAccDepartmentVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDepartmentVersionResponse")
	public void getAccDepartmentVersion(
			@WebParam(name = "GetAccDepartmentVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccDepartmentVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * ɾ���Ӧ����ԽӺŵĲ���
	 * 
	 * @param sThirdID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteAccDep", action = "http://www.hzsun.com/DeleteAccDep")
	@WebResult(name = "DeleteAccDepResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "DeleteAccDep", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteAccDep")
	@ResponseWrapper(localName = "DeleteAccDepResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteAccDepResponse")
	public String deleteAccDep(
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID);

	/**
	 * ���ӵ����Ų���
	 * 
	 * @param sThirdID
	 * @param nDepNum
	 * @param sParentThirdID
	 * @param uploadAccDepResult
	 * @param sDepName
	 */
	@WebMethod(operationName = "UploadAccDep", action = "http://www.hzsun.com/UploadAccDep")
	@RequestWrapper(localName = "UploadAccDep", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccDep")
	@ResponseWrapper(localName = "UploadAccDepResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccDepResponse")
	public void uploadAccDep(
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sParentThirdID", targetNamespace = "http://www.hzsun.com/") String sParentThirdID,
			@WebParam(name = "sDepName", targetNamespace = "http://www.hzsun.com/") String sDepName,
			@WebParam(name = "UploadAccDepResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> uploadAccDepResult,
			@WebParam(name = "nDepNum", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nDepNum);

	/**
	 * �޸ĵ����Ų���
	 * 
	 * @param sThirdID
	 * @param nDepNum
	 * @param sDepName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateAccDep", action = "http://www.hzsun.com/UpdateAccDep")
	@WebResult(name = "UpdateAccDepResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UpdateAccDep", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UpdateAccDep")
	@ResponseWrapper(localName = "UpdateAccDepResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UpdateAccDepResponse")
	public String updateAccDep(
			@WebParam(name = "nDepNum", targetNamespace = "http://www.hzsun.com/") int nDepNum,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sDepName", targetNamespace = "http://www.hzsun.com/") String sDepName);

	/**
	 * ��ȡ�����ֵ����(Json)
	 * 
	 * @param data
	 * @param getParmCodeResult
	 */
	@WebMethod(operationName = "GetParmCode", action = "http://www.hzsun.com/GetParmCode")
	@RequestWrapper(localName = "GetParmCode", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCode")
	@ResponseWrapper(localName = "GetParmCodeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCodeResponse")
	public void getParmCode(
			@WebParam(name = "GetParmCodeResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getParmCodeResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ�����ֵ����(Xml)
	 * 
	 * @param data
	 * @param getParmCodeForXmlResult
	 */
	@WebMethod(operationName = "GetParmCodeForXml", action = "http://www.hzsun.com/GetParmCodeForXml")
	@RequestWrapper(localName = "GetParmCodeForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCodeForXml")
	@ResponseWrapper(localName = "GetParmCodeForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCodeForXmlResponse")
	public void getParmCodeForXml(
			@WebParam(name = "GetParmCodeForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getParmCodeForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ�����ֵ�汾��
	 * 
	 * @param getParmCodeVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetParmCodeVersion", action = "http://www.hzsun.com/GetParmCodeVersion")
	@RequestWrapper(localName = "GetParmCodeVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCodeVersion")
	@ResponseWrapper(localName = "GetParmCodeVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParmCodeVersionResponse")
	public void getParmCodeVersion(
			@WebParam(name = "GetParmCodeVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getParmCodeVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * ɾ���Ӧ����ԽӺŵĴ����ֵ�
	 * 
	 * @param sThirdID
	 * @param sParamTypeThirdID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteParamCode", action = "http://www.hzsun.com/DeleteParamCode")
	@WebResult(name = "DeleteParamCodeResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "DeleteParamCode", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteParamCode")
	@ResponseWrapper(localName = "DeleteParamCodeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteParamCodeResponse")
	public String deleteParamCode(
			@WebParam(name = "sParamTypeThirdID", targetNamespace = "http://www.hzsun.com/") String sParamTypeThirdID,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID);

	/**
	 * �����޸ĵ�������ֵ����
	 * 
	 * @param sThirdID
	 * @param nParamNum
	 * @param sParmContent
	 * @param uploadParamCodeResult
	 * @param sParamTypeThirdID
	 */
	@WebMethod(operationName = "UploadParamCode", action = "http://www.hzsun.com/UploadParamCode")
	@RequestWrapper(localName = "UploadParamCode", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadParamCode")
	@ResponseWrapper(localName = "UploadParamCodeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadParamCodeResponse")
	public void uploadParamCode(
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sParamTypeThirdID", targetNamespace = "http://www.hzsun.com/") String sParamTypeThirdID,
			@WebParam(name = "sParmContent", targetNamespace = "http://www.hzsun.com/") String sParmContent,
			@WebParam(name = "UploadParamCodeResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> uploadParamCodeResult,
			@WebParam(name = "nParamNum", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nParamNum);

	/**
	 * �޸Ĵ����ֵ����
	 * 
	 * @param sThirdID
	 * @param nParaNum
	 * @param sParamContent
	 * @param sParamTypeThirdID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateParamCode", action = "http://www.hzsun.com/UpdateParamCode")
	@WebResult(name = "UpdateParamCodeResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UpdateParamCode", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UpdateParamCode")
	@ResponseWrapper(localName = "UpdateParamCodeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UpdateParamCodeResponse")
	public String updateParamCode(
			@WebParam(name = "nParaNum", targetNamespace = "http://www.hzsun.com/") int nParaNum,
			@WebParam(name = "sParamTypeThirdID", targetNamespace = "http://www.hzsun.com/") String sParamTypeThirdID,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sParamContent", targetNamespace = "http://www.hzsun.com/") String sParamContent);

	/**
	 * �޸ĵ������������
	 * 
	 * @param sThirdID
	 * @param nTypeNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UploadParamType", action = "http://www.hzsun.com/UploadParamType")
	@WebResult(name = "UploadParamTypeResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UploadParamType", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadParamType")
	@ResponseWrapper(localName = "UploadParamTypeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadParamTypeResponse")
	public String uploadParamType(
			@WebParam(name = "nTypeNum", targetNamespace = "http://www.hzsun.com/") int nTypeNum,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID);

	/**
	 * ��ȡ�������������(Json)
	 * 
	 * @param data
	 * @param getParamTypeResult
	 */
	@WebMethod(operationName = "GetParamType", action = "http://www.hzsun.com/GetParamType")
	@RequestWrapper(localName = "GetParamType", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParamType")
	@ResponseWrapper(localName = "GetParamTypeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParamTypeResponse")
	public void getParamType(
			@WebParam(name = "GetParamTypeResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getParamTypeResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ�������������(Xml)
	 * 
	 * @param getParamTypeForXmlResult
	 * @param data
	 */
	@WebMethod(operationName = "GetParamTypeForXml", action = "http://www.hzsun.com/GetParamTypeForXml")
	@RequestWrapper(localName = "GetParamTypeForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParamTypeForXml")
	@ResponseWrapper(localName = "GetParamTypeForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetParamTypeForXmlResponse")
	public void getParamTypeForXml(
			@WebParam(name = "GetParamTypeForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getParamTypeForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡָ���ʻ�����ϸ��Ϣ(Json)
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param data
	 * @param getAccInfoResult
	 */
	@WebMethod(operationName = "GetAccInfo", action = "http://www.hzsun.com/GetAccInfo")
	@RequestWrapper(localName = "GetAccInfo", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfo")
	@ResponseWrapper(localName = "GetAccInfoResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfoResponse")
	public void getAccInfo(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "GetAccInfoResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccInfoResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡָ���ʻ�����ϸ��Ϣ(Xml)
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param data
	 * @param getAccInfoForXmlResult
	 */
	@WebMethod(operationName = "GetAccInfoForXml", action = "http://www.hzsun.com/GetAccInfoForXml")
	@RequestWrapper(localName = "GetAccInfoForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfoForXml")
	@ResponseWrapper(localName = "GetAccInfoForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfoForXmlResponse")
	public void getAccInfoForXml(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "GetAccInfoForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccInfoForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡָ���ʻ�����Ƭ��Ϣ
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param data
	 * @param getAccPictureResult
	 */
	@WebMethod(operationName = "GetAccPicture", action = "http://www.hzsun.com/GetAccPicture")
	@RequestWrapper(localName = "GetAccPicture", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPicture")
	@ResponseWrapper(localName = "GetAccPictureResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPictureResponse")
	public void getAccPicture(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "GetAccPictureResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccPictureResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<byte[]> data);

	/**
	 * ��ȡ�ʻ���Ƭ��Ϣ
	 * 
	 * @param nCount
	 * @param getAccPicturesResult
	 * @param nCurrVersion
	 * @param data
	 * @param version
	 */
	@WebMethod(operationName = "GetAccPictures", action = "http://www.hzsun.com/GetAccPictures")
	@RequestWrapper(localName = "GetAccPictures", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPictures")
	@ResponseWrapper(localName = "GetAccPicturesResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPicturesResponse")
	public void getAccPictures(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "nCount", targetNamespace = "http://www.hzsun.com/") int nCount,
			@WebParam(name = "GetAccPicturesResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccPicturesResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<byte[]> data,
			@WebParam(name = "nCurrVersion", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nCurrVersion);

	/**
	 * ��ȡ�ʻ���Ƭ�汾��
	 * 
	 * @param getAccPictureVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetAccPictureVersion", action = "http://www.hzsun.com/GetAccPictureVersion")
	@RequestWrapper(localName = "GetAccPictureVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPictureVersion")
	@ResponseWrapper(localName = "GetAccPictureVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccPictureVersionResponse")
	public void getAccPictureVersion(
			@WebParam(name = "GetAccPictureVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccPictureVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * ��ȡ�ʻ�����Ϣ(Json)
	 * 
	 * @param nCount
	 * @param nCurrVersion
	 * @param data
	 * @param getBaseAccInfosResult
	 * @param version
	 */
	@WebMethod(operationName = "GetBaseAccInfos", action = "http://www.hzsun.com/GetBaseAccInfos")
	@RequestWrapper(localName = "GetBaseAccInfos", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBaseAccInfos")
	@ResponseWrapper(localName = "GetBaseAccInfosResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBaseAccInfosResponse")
	public void getBaseAccInfos(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "nCount", targetNamespace = "http://www.hzsun.com/") int nCount,
			@WebParam(name = "GetBaseAccInfosResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getBaseAccInfosResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data,
			@WebParam(name = "nCurrVersion", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nCurrVersion);

	/**
	 * ��ȡ�ʻ�����Ϣ(Xml)
	 * 
	 * @param getBaseAccInfosForXmlResult
	 * @param nCount
	 * @param nCurrVersion
	 * @param data
	 * @param version
	 */
	@WebMethod(operationName = "GetBaseAccInfosForXml", action = "http://www.hzsun.com/GetBaseAccInfosForXml")
	@RequestWrapper(localName = "GetBaseAccInfosForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBaseAccInfosForXml")
	@ResponseWrapper(localName = "GetBaseAccInfosForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBaseAccInfosForXmlResponse")
	public void getBaseAccInfosForXml(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "nCount", targetNamespace = "http://www.hzsun.com/") int nCount,
			@WebParam(name = "GetBaseAccInfosForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getBaseAccInfosForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data,
			@WebParam(name = "nCurrVersion", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nCurrVersion);

	/**
	 * ��ȡ�ʻ�������Ϣ(Json)
	 * 
	 * @param nCount
	 * @param nCurrVersion
	 * @param data
	 * @param getCompleteAccInfosResult
	 * @param version
	 */
	@WebMethod(operationName = "GetCompleteAccInfos", action = "http://www.hzsun.com/GetCompleteAccInfos")
	@RequestWrapper(localName = "GetCompleteAccInfos", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetCompleteAccInfos")
	@ResponseWrapper(localName = "GetCompleteAccInfosResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetCompleteAccInfosResponse")
	public void getCompleteAccInfos(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "nCount", targetNamespace = "http://www.hzsun.com/") int nCount,
			@WebParam(name = "GetCompleteAccInfosResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getCompleteAccInfosResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data,
			@WebParam(name = "nCurrVersion", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nCurrVersion);

	/**
	 * ��ȡ�ʻ�������Ϣ(Xml)
	 * 
	 * @param nCount
	 * @param getCompleteAccInfosForXmlResult
	 * @param nCurrVersion
	 * @param data
	 * @param version
	 */
	@WebMethod(operationName = "GetCompleteAccInfosForXml", action = "http://www.hzsun.com/GetCompleteAccInfosForXml")
	@RequestWrapper(localName = "GetCompleteAccInfosForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetCompleteAccInfosForXml")
	@ResponseWrapper(localName = "GetCompleteAccInfosForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetCompleteAccInfosForXmlResponse")
	public void getCompleteAccInfosForXml(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "nCount", targetNamespace = "http://www.hzsun.com/") int nCount,
			@WebParam(name = "GetCompleteAccInfosForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getCompleteAccInfosForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data,
			@WebParam(name = "nCurrVersion", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nCurrVersion);

	/**
	 * ��ȡ�ʻ���Ϣ�汾��
	 * 
	 * @param getAccInfoVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetAccInfoVersion", action = "http://www.hzsun.com/GetAccInfoVersion")
	@RequestWrapper(localName = "GetAccInfoVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfoVersion")
	@ResponseWrapper(localName = "GetAccInfoVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccInfoVersionResponse")
	public void getAccInfoVersion(
			@WebParam(name = "GetAccInfoVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccInfoVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * ��ȡָ���汾��֮��ĺ���(Json)
	 * 
	 * @param data
	 * @param getBlackListChgResult
	 * @param version
	 */
	@WebMethod(operationName = "GetBlackListChg", action = "http://www.hzsun.com/GetBlackListChg")
	@RequestWrapper(localName = "GetBlackListChg", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChg")
	@ResponseWrapper(localName = "GetBlackListChgResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChgResponse")
	public void getBlackListChg(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "GetBlackListChgResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getBlackListChgResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡָ���汾��֮��ĺ���(Xml)
	 * 
	 * @param getBlackListChgForXmlResult
	 * @param data
	 * @param version
	 */
	@WebMethod(operationName = "GetBlackListChgForXml", action = "http://www.hzsun.com/GetBlackListChgForXml")
	@RequestWrapper(localName = "GetBlackListChgForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChgForXml")
	@ResponseWrapper(localName = "GetBlackListChgForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChgForXmlResponse")
	public void getBlackListChgForXml(
			@WebParam(name = "version", targetNamespace = "http://www.hzsun.com/") int version,
			@WebParam(name = "GetBlackListChgForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getBlackListChgForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ȡ����汾��
	 * 
	 * @param getBlackListChgVersionResult
	 * @param version
	 */
	@WebMethod(operationName = "GetBlackListChgVersion", action = "http://www.hzsun.com/GetBlackListChgVersion")
	@RequestWrapper(localName = "GetBlackListChgVersion", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChgVersion")
	@ResponseWrapper(localName = "GetBlackListChgVersionResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetBlackListChgVersionResponse")
	public void getBlackListChgVersion(
			@WebParam(name = "GetBlackListChgVersionResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getBlackListChgVersionResult,
			@WebParam(name = "Version", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> version);

	/**
	 * �����޸ĵ��������
	 * 
	 * @param sThirdID
	 * @param sPost
	 * @param sAreaNo
	 * @param uploadAccInfoResult
	 * @param dtEnterTime
	 * @param sDuty
	 * @param operatorNum
	 * @param dtBirthDay
	 * @param sPerCode
	 * @param sAccSex
	 * @param sMobileCode
	 * @param sTech
	 * @param sArcClass
	 * @param sDepNo
	 * @param stanum
	 * @param nAccNum
	 * @param sCertCode
	 * @param sPostCode
	 * @param sCertType
	 * @param sClsNo
	 * @param sNation
	 * @param sAccName
	 * @param sPolity
	 * @param sEMail
	 */
	@WebMethod(operationName = "UploadAccInfo", action = "http://www.hzsun.com/UploadAccInfo")
	@RequestWrapper(localName = "UploadAccInfo", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccInfo")
	@ResponseWrapper(localName = "UploadAccInfoResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccInfoResponse")
	public void uploadAccInfo(
			@WebParam(name = "operatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "sPerCode", targetNamespace = "http://www.hzsun.com/") String sPerCode,
			@WebParam(name = "sAreaNo", targetNamespace = "http://www.hzsun.com/") String sAreaNo,
			@WebParam(name = "sAccName", targetNamespace = "http://www.hzsun.com/") String sAccName,
			@WebParam(name = "sDepNo", targetNamespace = "http://www.hzsun.com/") String sDepNo,
			@WebParam(name = "sClsNo", targetNamespace = "http://www.hzsun.com/") String sClsNo,
			@WebParam(name = "sAccSex", targetNamespace = "http://www.hzsun.com/") String sAccSex,
			@WebParam(name = "sMobileCode", targetNamespace = "http://www.hzsun.com/") String sMobileCode,
			@WebParam(name = "sEMail", targetNamespace = "http://www.hzsun.com/") String sEMail,
			@WebParam(name = "sPostCode", targetNamespace = "http://www.hzsun.com/") String sPostCode,
			@WebParam(name = "sCertType", targetNamespace = "http://www.hzsun.com/") String sCertType,
			@WebParam(name = "sCertCode", targetNamespace = "http://www.hzsun.com/") String sCertCode,
			@WebParam(name = "sArcClass", targetNamespace = "http://www.hzsun.com/") String sArcClass,
			@WebParam(name = "sNation", targetNamespace = "http://www.hzsun.com/") String sNation,
			@WebParam(name = "sPolity", targetNamespace = "http://www.hzsun.com/") String sPolity,
			@WebParam(name = "sDuty", targetNamespace = "http://www.hzsun.com/") String sDuty,
			@WebParam(name = "sTech", targetNamespace = "http://www.hzsun.com/") String sTech,
			@WebParam(name = "sPost", targetNamespace = "http://www.hzsun.com/") String sPost,
			@WebParam(name = "dtEnterTime", targetNamespace = "http://www.hzsun.com/") XMLGregorianCalendar dtEnterTime,
			@WebParam(name = "dtBirthDay", targetNamespace = "http://www.hzsun.com/") XMLGregorianCalendar dtBirthDay,
			@WebParam(name = "UploadAccInfoResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> uploadAccInfoResult,
			@WebParam(name = "nAccNum", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nAccNum);

	/**
	 * ɾ���Ӧ����ԽӺŵĿ�����Ƭ
	 * 
	 * @param sThirdID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteAccPic", action = "http://www.hzsun.com/DeleteAccPic")
	@WebResult(name = "DeleteAccPicResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "DeleteAccPic", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteAccPic")
	@ResponseWrapper(localName = "DeleteAccPicResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DeleteAccPicResponse")
	public String deleteAccPic(
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID);

	/**
	 * �����޸ĵ������Ƭ����
	 * 
	 * @param sThirdID
	 * @param bytePic
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UploadAccPic", action = "http://www.hzsun.com/UploadAccPic")
	@WebResult(name = "UploadAccPicResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UploadAccPic", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccPic")
	@ResponseWrapper(localName = "UploadAccPicResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UploadAccPicResponse")
	public String uploadAccPic(
			@WebParam(name = "sThirdID", targetNamespace = "http://www.hzsun.com/") String sThirdID,
			@WebParam(name = "bytePic", targetNamespace = "http://www.hzsun.com/") byte[] bytePic);

	/**
	 * ǩ��
	 * 
	 * @param secret1
	 * @param thirdType
	 * @param stanum
	 * @param secret2
	 * @param signInResult
	 */
	@WebMethod(operationName = "SignIn", action = "http://www.hzsun.com/SignIn")
	@RequestWrapper(localName = "SignIn", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.SignIn")
	@ResponseWrapper(localName = "SignInResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.SignInResponse")
	public void signIn(
			@WebParam(name = "SignInResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> signInResult,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> stanum,
			@WebParam(name = "ThirdType", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> thirdType,
			@WebParam(name = "Secret1", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> secret1,
			@WebParam(name = "Secret2", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> secret2);

	/**
	 * �޸Ŀ�����ѯ����
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param newPassword
	 * @param sIDNo
	 * @param oldPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ChangeQueryPassword", action = "http://www.hzsun.com/ChangeQueryPassword")
	@WebResult(name = "ChangeQueryPasswordResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "ChangeQueryPassword", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ChangeQueryPassword")
	@ResponseWrapper(localName = "ChangeQueryPasswordResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ChangeQueryPasswordResponse")
	public String changeQueryPassword(
			@WebParam(name = "operatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "oldPassword", targetNamespace = "http://www.hzsun.com/") String oldPassword,
			@WebParam(name = "newPassword", targetNamespace = "http://www.hzsun.com/") String newPassword);

	/**
	 * �޸Ŀ�����������
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param newPassword
	 * @param sIDNo
	 * @param oldPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ChangePayPassword", action = "http://www.hzsun.com/ChangePayPassword")
	@WebResult(name = "ChangePayPasswordResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "ChangePayPassword", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ChangePayPassword")
	@ResponseWrapper(localName = "ChangePayPasswordResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ChangePayPasswordResponse")
	public String changePayPassword(
			@WebParam(name = "operatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "oldPassword", targetNamespace = "http://www.hzsun.com/") String oldPassword,
			@WebParam(name = "newPassword", targetNamespace = "http://www.hzsun.com/") String newPassword);

	/**
	 * �����Ĺ�ʧ
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param sIDNo
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ReportLoss", action = "http://www.hzsun.com/ReportLoss")
	@WebResult(name = "ReportLossResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "ReportLoss", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ReportLoss")
	@ResponseWrapper(localName = "ReportLossResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ReportLossResponse")
	public String reportLoss(
			@WebParam(name = "operatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "password", targetNamespace = "http://www.hzsun.com/") String password);

	/**
	 * �����Ľ��
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param sIDNo
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FreeLoss", action = "http://www.hzsun.com/FreeLoss")
	@WebResult(name = "FreeLossResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "FreeLoss", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.FreeLoss")
	@ResponseWrapper(localName = "FreeLossResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.FreeLossResponse")
	public String freeLoss(
			@WebParam(name = "operatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "password", targetNamespace = "http://www.hzsun.com/") String password);

	/**
	 * �����Ķ���
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param sIDNo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Freeze", action = "http://www.hzsun.com/Freeze")
	@WebResult(name = "FreezeResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "Freeze", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.Freeze")
	@ResponseWrapper(localName = "FreezeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.FreezeResponse")
	public String freeze(
			@WebParam(name = "OperatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType);

	/**
	 * �����Ľⶳ
	 * 
	 * @param nIDType
	 * @param stanum
	 * @param operatorNum
	 * @param sIDNo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UnFreeze", action = "http://www.hzsun.com/UnFreeze")
	@WebResult(name = "UnFreezeResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "UnFreeze", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UnFreeze")
	@ResponseWrapper(localName = "UnFreezeResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.UnFreezeResponse")
	public String unFreeze(
			@WebParam(name = "OperatorNum", targetNamespace = "http://www.hzsun.com/") int operatorNum,
			@WebParam(name = "stanum", targetNamespace = "http://www.hzsun.com/") int stanum,
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType);

	/**
	 * ��ȡ�ʻ�״̬
	 * 
	 * @param nIDType
	 * @param getAccStatusResult
	 * @param sIDNo
	 * @param bValid
	 */
	@WebMethod(operationName = "GetAccStatus", action = "http://www.hzsun.com/GetAccStatus")
	@RequestWrapper(localName = "GetAccStatus", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccStatus")
	@ResponseWrapper(localName = "GetAccStatusResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccStatusResponse")
	public void getAccStatus(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "GetAccStatusResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccStatusResult,
			@WebParam(name = "bValid", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Boolean> bValid);

	/**
	 * ��֤��������
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ValidatePayPassword", action = "http://www.hzsun.com/ValidatePayPassword")
	@WebResult(name = "ValidatePayPasswordResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "ValidatePayPassword", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ValidatePayPassword")
	@ResponseWrapper(localName = "ValidatePayPasswordResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ValidatePayPasswordResponse")
	public String validatePayPassword(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "Password", targetNamespace = "http://www.hzsun.com/") String password);

	/**
	 * ��֤��ѯ����
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ValidateQueryPassword", action = "http://www.hzsun.com/ValidateQueryPassword")
	@WebResult(name = "ValidateQueryPasswordResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "ValidateQueryPassword", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ValidateQueryPassword")
	@ResponseWrapper(localName = "ValidateQueryPasswordResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.ValidateQueryPasswordResponse")
	public String validateQueryPassword(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "Password", targetNamespace = "http://www.hzsun.com/") String password);

	/**
	 * ��ȡ�ֿ������п���
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param getAccBankCardNoResult
	 * @param sBankCardNo
	 */
	@WebMethod(operationName = "GetAccBankCardNo", action = "http://www.hzsun.com/GetAccBankCardNo")
	@RequestWrapper(localName = "GetAccBankCardNo", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccBankCardNo")
	@ResponseWrapper(localName = "GetAccBankCardNoResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccBankCardNoResponse")
	public void getAccBankCardNo(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "GetAccBankCardNoResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccBankCardNoResult,
			@WebParam(name = "sBankCardNo", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> sBankCardNo);

	/**
	 * ��ȡ���������
	 * 
	 * @param nIDType
	 * @param sIDNo
	 * @param nMoney
	 * @param getAccDBMoneyResult
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "GetAccDBMoney", action = "http://www.hzsun.com/GetAccDBMoney")
	@RequestWrapper(localName = "GetAccDBMoney", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDBMoney")
	@ResponseWrapper(localName = "GetAccDBMoneyResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetAccDBMoneyResponse")
	public void getAccDBMoney(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "GetAccDBMoneyResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getAccDBMoneyResult,
			@WebParam(name = "nMoney", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Integer> nMoney);

	/**
	 * �����շ�
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param nDealerNum
	 * @param nOptNum
	 * @param nStaSID
	 * @param nStaNum
	 * @param sIDNo
	 * @param paymentResult
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "Payment", action = "http://www.hzsun.com/Payment")
	@RequestWrapper(localName = "Payment", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.Payment")
	@ResponseWrapper(localName = "PaymentResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.PaymentResponse")
	public void payment(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "PaymentResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> paymentResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * �շѳ���
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param nDealerNum
	 * @param nOptNum
	 * @param nStaSID
	 * @param antiPaymentResult
	 * @param nStaNum
	 * @param sIDNo
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "AntiPayment", action = "http://www.hzsun.com/AntiPayment")
	@RequestWrapper(localName = "AntiPayment", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.AntiPayment")
	@ResponseWrapper(localName = "AntiPaymentResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.AntiPaymentResponse")
	public void antiPayment(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "AntiPaymentResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> antiPaymentResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * �޿���ֵ
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param nOptNum
	 * @param nStaSID
	 * @param nStaNum
	 * @param sIDNo
	 * @param depositResult
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "Deposit", action = "http://www.hzsun.com/Deposit")
	@RequestWrapper(localName = "Deposit", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.Deposit")
	@ResponseWrapper(localName = "DepositResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DepositResponse")
	public void deposit(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "DepositResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> depositResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * �����շ�(����ʱ��)
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param nDealerNum
	 * @param nOptNum
	 * @param nStaSID
	 * @param nStaNum
	 * @param sIDNo
	 * @param paymentAResult
	 * @param sDealTime
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "PaymentA", action = "http://www.hzsun.com/PaymentA")
	@RequestWrapper(localName = "PaymentA", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.PaymentA")
	@ResponseWrapper(localName = "PaymentAResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.PaymentAResponse")
	public void paymentA(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "sDealTime", targetNamespace = "http://www.hzsun.com/") String sDealTime,
			@WebParam(name = "PaymentAResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> paymentAResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * �շѳ���(����ʱ��)
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param antiPaymentAResult
	 * @param nDealerNum
	 * @param nOptNum
	 * @param nStaSID
	 * @param nStaNum
	 * @param sIDNo
	 * @param sDealTime
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "AntiPaymentA", action = "http://www.hzsun.com/AntiPaymentA")
	@RequestWrapper(localName = "AntiPaymentA", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.AntiPaymentA")
	@ResponseWrapper(localName = "AntiPaymentAResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.AntiPaymentAResponse")
	public void antiPaymentA(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "sDealTime", targetNamespace = "http://www.hzsun.com/") String sDealTime,
			@WebParam(name = "AntiPaymentAResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> antiPaymentAResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * �޿���ֵ(����ʱ��)
	 * 
	 * @param nMonDeal
	 * @param nIDType
	 * @param nOptNum
	 * @param nStaSID
	 * @param nStaNum
	 * @param sIDNo
	 * @param depositAResult
	 * @param sDealTime
	 * @param nEWalletNum
	 */
	@WebMethod(operationName = "DepositA", action = "http://www.hzsun.com/DepositA")
	@RequestWrapper(localName = "DepositA", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DepositA")
	@ResponseWrapper(localName = "DepositAResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.DepositAResponse")
	public void depositA(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonDeal", targetNamespace = "http://www.hzsun.com/") int nMonDeal,
			@WebParam(name = "sDealTime", targetNamespace = "http://www.hzsun.com/") String sDealTime,
			@WebParam(name = "DepositAResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> depositAResult,
			@WebParam(name = "nStaSID", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<Long> nStaSID);

	/**
	 * ��ѯ����������ˮ(Json)
	 * 
	 * @param nIDType
	 * @param nDealerNum
	 * @param nStaNum
	 * @param sIDNo
	 * @param data
	 * @param sBeginDate
	 * @param sEndDate
	 * @param getPaymentBooksResult
	 * @param nTerminalNum
	 */
	@WebMethod(operationName = "GetPaymentBooks", action = "http://www.hzsun.com/GetPaymentBooks")
	@RequestWrapper(localName = "GetPaymentBooks", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetPaymentBooks")
	@ResponseWrapper(localName = "GetPaymentBooksResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetPaymentBooksResponse")
	public void getPaymentBooks(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "sBeginDate", targetNamespace = "http://www.hzsun.com/") String sBeginDate,
			@WebParam(name = "sEndDate", targetNamespace = "http://www.hzsun.com/") String sEndDate,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nTerminalNum", targetNamespace = "http://www.hzsun.com/") int nTerminalNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "GetPaymentBooksResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getPaymentBooksResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ��ѯ����������ˮ(Xml)
	 * 
	 * @param nIDType
	 * @param nDealerNum
	 * @param nStaNum
	 * @param sIDNo
	 * @param data
	 * @param sBeginDate
	 * @param getPaymentBooksForXmlResult
	 * @param sEndDate
	 * @param nTerminalNum
	 */
	@WebMethod(operationName = "GetPaymentBooksForXml", action = "http://www.hzsun.com/GetPaymentBooksForXml")
	@RequestWrapper(localName = "GetPaymentBooksForXml", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetPaymentBooksForXml")
	@ResponseWrapper(localName = "GetPaymentBooksForXmlResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetPaymentBooksForXmlResponse")
	public void getPaymentBooksForXml(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "sBeginDate", targetNamespace = "http://www.hzsun.com/") String sBeginDate,
			@WebParam(name = "sEndDate", targetNamespace = "http://www.hzsun.com/") String sEndDate,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nTerminalNum", targetNamespace = "http://www.hzsun.com/") int nTerminalNum,
			@WebParam(name = "nDealerNum", targetNamespace = "http://www.hzsun.com/") int nDealerNum,
			@WebParam(name = "GetPaymentBooksForXmlResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getPaymentBooksForXmlResult,
			@WebParam(name = "Data", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> data);

	/**
	 * ���Ÿ��˲���
	 * 
	 * @param nIDType
	 * @param nOptNum
	 * @param nStaNum
	 * @param sIDNo
	 * @param nMonSubsidy
	 * @param nEWalletNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GrantSubsidy", action = "http://www.hzsun.com/GrantSubsidy")
	@WebResult(name = "GrantSubsidyResult", targetNamespace = "http://www.hzsun.com/")
	@RequestWrapper(localName = "GrantSubsidy", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GrantSubsidy")
	@ResponseWrapper(localName = "GrantSubsidyResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GrantSubsidyResponse")
	public String grantSubsidy(
			@WebParam(name = "sIDNo", targetNamespace = "http://www.hzsun.com/") String sIDNo,
			@WebParam(name = "nIDType", targetNamespace = "http://www.hzsun.com/") int nIDType,
			@WebParam(name = "nStaNum", targetNamespace = "http://www.hzsun.com/") int nStaNum,
			@WebParam(name = "nOptNum", targetNamespace = "http://www.hzsun.com/") int nOptNum,
			@WebParam(name = "nEWalletNum", targetNamespace = "http://www.hzsun.com/") int nEWalletNum,
			@WebParam(name = "nMonSubsidy", targetNamespace = "http://www.hzsun.com/") int nMonSubsidy);

	/**
	 * ��ȡ�쳣��������
	 * 
	 * @param sErrCode
	 * @param getErrTxtResult
	 * @param sErrTxt
	 */
	@WebMethod(operationName = "GetErrTxt", action = "http://www.hzsun.com/GetErrTxt")
	@RequestWrapper(localName = "GetErrTxt", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetErrTxt")
	@ResponseWrapper(localName = "GetErrTxtResponse", targetNamespace = "http://www.hzsun.com/", className = "com.hzsun.GetErrTxtResponse")
	public void getErrTxt(
			@WebParam(name = "sErrCode", targetNamespace = "http://www.hzsun.com/") String sErrCode,
			@WebParam(name = "GetErrTxtResult", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> getErrTxtResult,
			@WebParam(name = "sErrTxt", targetNamespace = "http://www.hzsun.com/", mode = WebParam.Mode.OUT) Holder<String> sErrTxt);

}
